### ISSUE TITLE
libzmq.dll missing - Huh?

### ISSUE THREAD

**Issue by RIL-** [bvarga/delphizmq#15]
Hi,

I'm missing the file libzmq.dll. Why isn't it included in the installers?

I noticed that it was mentioned in the README that the dll could be downloaded - and renamed. But what's the name of the file to be downloaded if its not libzmq.dll? (I only found an old libzmq for version 2.7 something from 2010, but I presume that's not what I want for the 4.x version of ZMQ?)

I would prefer using ZMQ 4.1, but I couldn't find neither installers nor dll's for that version (installers exist only for latest stable 4.0.4 http://zeromq.org/distro:microsoft-windows ).

I'm using Win7 (x64) and D2007 up tp XE5. Does it matter much which version of ZMQ (x32 or x64)?

If there's no other way to get the libzmq.dll than to compile the sources myself, where can I find detailed instructions for how to do that? (I've no idea about how that's done). 

To me it seems like ZMQ is a strange project when it doesn't keep all files, or at least links to files, in one place.

I would be very thankful for any help.

Best regards,
// Rolf Lampa

**Comment by bvarga** [comment]
Hello,

Seems like installers exist only for the 4.0.4 version. I can't check it now, but I'm sure the installer has the dlls, after running the exe, it will install the dlls somewhere into your Program Files folder into a directory called ZMQ v4.x or something like that.  

If you want the newest, you should read the instructions on http://zeromq.org/intro:get-the-software how to build your own.

you can find the source codes in the github: https://github.com/zeromq


regards
B.

**Comment by RIL-** [comment]
Hi again,
I can now compile my program in Delphi (2007) after using the installer (4.0.4) and renaming the file "libzmq-v120-mt-4_0_4.dll" in the bin folder into "libzmq.dll".

I also tried installing the vs2013 and running buildall.bat in the folder "Z:\DEV\GitHub\ZeroMQ4-1\builds\msvc\build\buildall.bat", but compilation seems to fail with the following log:
http://wiki.rilpartner.se/wiki/User:RIL/ZeroMQ4-1/builds/msvc/build/build_12.log

To me the whole CPP thing is more foreign than Arabic, so I don't benefit much from the log (but it seems to keep complaining about the file "libzmq.lib" and it obviously has problems with "libsodium.lib" as well. Therefore I downloaded libsodium and compiled with the following log:
http://wiki.rilpartner.se/wiki/User:RIL/libsodium/builds/msvc/build/build_12.log

Perhaps the two projects must explicitly know about each other but if so, I don't know how/where to define import paths for the ZMQ project. I would have expected the ZeroMQ4-1 project to have complete sources though, but I obviously don't understand the logs.

On my local machine both ZeroMQ4-1 and libsodium reside under Z:\DEV\GitHub\ 
Z:\DEV\GitHub\libsodium\builds\...\build_12.log and 
Z:\DEV\GitHub\ZeroMQ4-1\builds\...\build_12.log

Obviously the instruction doesn't help all the way unless already knowing more about CPP folder structures, VS and all kinds of stuff which I'm entirely agnostic about, so therefore I'd apprechiate additional help about how to compile the sources and where to expect to find the resulting dll's when the "Solutions" file seems to be located in this folder:
Z:\DEV\GitHub\ZeroMQ4-1\builds\msvc\vs2013
(there are also vs2008, vs2010, vs2011 and vs2012 folders at the same level as the "build" foilder containing the build.bat files)

// Rolf Lampa

**Comment by bvarga** [comment]
Hello,

Sorry, I don't have windows at the moment, so I can help with these, and it's not related to this binding, so I close this thread. There are threads on the mailing list about building on windows, where you can ask for help, see the community page at [zeromq.org](http://zeromq.org/community)

note that the master branch of this repo only supports zeromq without curve, but there are experimantal support (updated long time ago) in the develop branch.

Any other questions notes about this binding is always welcome.
